language: c++
matrix:
        include:
                os: linux
                addons:
                        sources:
                                - ubuntu-toolchain-r test
                        packages:
                                - g++ 9
script: make test
