language: c++
matrix:
        include:
                os: linux
                addons:
                        apt:
                                sources:
                                        - ubuntu-toolchain-r-test
                                packages:
                                        - g++-8

before_install:
        - ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
        - ln -s /usr/bin/g++-8 /usr/local/bin/g++
        - g++ --version

script: make test
