dist: trusty
sudo: required
language: cpp
addons:
        apt:
                sources:
                        - ubuntu-toolchain-r-test
                packages:
                        - g++-9
                        - librapidxml-dev

before_install:

script: 
        - sudo ln -s /usr/bin/gcc-9 /usr/local/bin/gcc
        - sudo ln -s /usr/bin/g++-9 /usr/local/bin/g++
        - g++ --version
        - make test
