sudo: required
language: c++
addons:
        apt:
                sources:
                        - ubuntu-toolchain-r-test
                packages:
                        - g++-8

before_install:

script: 
        - ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
        - ln -s /usr/bin/g++-8 /usr/local/bin/g++
        - g++ --version
        - make test
