matrix:
        include:
                os: linux
                addons:
                        apt:
                                sources:
                                        - ubuntu-toolchain-r test
                                packages:
                                        - g++ 9
                env:
                        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before-install:
        eval "${MATRIX_EVAL}"
script: make test
