name: NetCHASM CI
on: [push]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: mdbm
        uses: actions/checkout@v2
        with:
          repository: timrc-git/mdbm
          path: mdbm
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: NetCHASM
      - name: build
        uses: ./NetCHASM/.github/actions/build